/**
 * Load pre-computed bill summaries (CRS + AI beneficiary analysis).
 * Generated by scripts/fetch-bill-summaries.ts
 */
import type { BillSummary } from "./types";

let cached: Record<string, BillSummary> | null = null;

export function loadBillSummaries(): Record<string, BillSummary> {
  if (cached) return cached;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    cached = require("@/data/bill-summaries.json") as Record<string, BillSummary>;
    return cached;
  } catch {
    return {};
  }
}

export function getBillSummary(
  data: Record<string, BillSummary>,
  billId: string
): BillSummary | null {
  return data[billId] ?? null;
}
