import { describe, it, expect } from "vitest";
import { FACTOR_WEIGHTS, FACTOR_WEIGHTS_NO_BIPARTISAN } from "./alignment-enhanced";
import alignmentScores from "../data/alignment-scores.json";

describe("data integrity guards", () => {
  it("composite score factor weights sum to 100%", () => {
    const full = Object.values(FACTOR_WEIGHTS).reduce((a, b) => a + b, 0);
    const noBipartisan = Object.values(FACTOR_WEIGHTS_NO_BIPARTISAN).reduce(
      (a, b) => a + b,
      0
    );
    expect(full).toBeCloseTo(1.0, 10);
    expect(noBipartisan).toBeCloseTo(1.0, 10);
  });

  it("alignment scores were generated by the v3 methodology", () => {
    // The v2 pipeline produced direction-inverted scores (see
    // REVIEW-AND-REMEDIATION-PLAN.md P0.1). Guard against ever shipping
    // v2-shaped data again.
    const records = alignmentScores as Array<Record<string, unknown>>;
    expect(records.length).toBeGreaterThan(0);
    for (const record of records) {
      expect(record).toHaveProperty("say_vs_do_v3");
    }
  });

  it("alignment scores include a confidence level for every member", () => {
    const records = alignmentScores as Array<{ confidence?: string }>;
    for (const record of records) {
      expect(["high", "medium", "low", "insufficient"]).toContain(
        record.confidence
      );
    }
  });
});
