import { getMember, getMembers, getMemberFinance, getMemberDisclosures } from "@/lib/data";
import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import DonorAnalysisSection from "@/components/DonorAnalysisSection";
import DonorCaptureScore from "@/components/DonorCaptureScore";
import MemberVotingRecord from "@/components/MemberVotingRecord";
import CommitteeMemberships from "@/components/CommitteeMemberships";
import StockTradesSection from "@/components/StockTradesSection";
import FinancialDisclosuresSection from "@/components/FinancialDisclosuresSection";
import ScandalsSection from "@/components/ScandalsSection";
import RepresentativeImage from "@/components/RepresentativeImage";
import SocialShare from "@/components/SocialShare";
import ConflictOfInterestSection from "@/components/ConflictOfInterestSection";
import ConflictCalloutSection from "@/components/ConflictCallout";
import ErrorBoundary from "@/components/ErrorBoundary";
import { generatePersonSchema, generateBreadcrumbSchema, structuredDataScript } from "@/lib/schema";
import { isLeader } from "@/lib/leadership";
import LatestNews from "@/components/LatestNews";
import { getConflictCallouts } from "@/lib/conflict-callouts";
import { detectConflicts } from "@/lib/conflict-detector";
import { INDUSTRIES } from "@/lib/industry-classifier";
import type { IndustryTotal } from "@/lib/industry-classifier";
import { loadDonorPercentiles } from "@/lib/donor-percentiles";
import { getMemberAlignmentEnhanced } from "@/lib/data-enhanced";
import { getConstituentAlignment } from "@/lib/constituent-alignment";
import RepresentsYouSection from "@/components/RepresentsYouSection";
import { RepVerdictBadge } from "@/components/RepVerdictBadge";
import InDevelopmentBanner from "@/components/InDevelopmentBanner";

import keyVotesData from "@/data/key-votes.json";
import bioguideToIcpsrData from "@/data/bioguide-to-icpsr.json";

// Optional static news cache (generated by `pnpm run research:fetch`)
// Declared but populated only if the cache file exists at build time
const newsCache: Record<string, { name: string; summary: string; citations: string[]; fetchedAt: string }> | undefined = undefined;

export function generateStaticParams() {
  return getMembers().map((member) => ({
    id: member.bioguide_id,
  }));
}

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const member = getMember(id);

  if (!member) {
    return {
      title: "Representative Not Found",
    };
  }

  const partyName = member.party === "D" ? "Democrat" : member.party === "R" ? "Republican" : "Independent";
  const chamberName = member.chamber === "house" ? "Representative" : "Senator";
  const district = member.district ? ` (${member.state}-${member.district})` : ` (${member.state})`;

  const ogTitle = `${member.full_name} - ${chamberName}${district}`;
  const ogDescription = `${partyName} ${chamberName} ${member.full_name}. View voting record, campaign finance data, alignment scores, stock trades, and accountability metrics.`;

  return {
    title: ogTitle,
    description: ogDescription,
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: `${member.full_name} accountability profile`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: ogDescription,
      images: ["/og-image.png"],
    },
  };
}

export default async function RepPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const member = getMember(id);

  if (!member) {
    notFound();
  }

  // Get real finance data from OpenFEC API
  const finance = await getMemberFinance(id);

  // Load pre-computed peer-comparison percentiles (build-time static data)
  const donorPercentiles = loadDonorPercentiles();
  
  // Detect conflicts of interest between donors and votes
  let conflicts: Array<{
    industry: string;
    industryDisplayName: string;
    icon: string;
    donationAmount: number;
    voteCategory: string;
    voteTitle: string;
    voteBill: string;
    voteDate: string;
    votePosition: "Yea" | "Nay" | "Present";
    expectedVote: "Yea" | "Nay";
    benefitsIndustry: boolean;
    conflictSeverity: "high" | "medium" | "low";
    explanation: string;
  }> = [];

  const icpsrId = (bioguideToIcpsrData as Record<string, string>)[id];

  if (finance && finance.top_industries && finance.top_industries.length > 0) {
    try {
      // Map static finance.top_industries to IndustryTotal[] using INDUSTRIES constant
      const industries: IndustryTotal[] = finance.top_industries
        .map((ind) => {
          const config = INDUSTRIES[ind.industry];
          return {
            industry: ind.industry,
            displayName: config?.name ?? ind.industry,
            icon: config?.icon ?? "📊",
            total: ind.total,
            count: 0,
            topContributors: [],
          };
        })
        .filter((ind) => ind.total > 0);

      // Get member's votes from keyVotesData using ICPSR ID (key-votes.json is keyed by ICPSR)
      const memberVotes = (keyVotesData as unknown as Array<{ bill: string; title: string; description: string; category: string; date: string; votes: Record<string, string> }>)
        .filter(vote => vote.votes && (icpsrId ? vote.votes[icpsrId] : undefined))
        .map(vote => ({
          bill: vote.bill,
          title: vote.title,
          category: vote.category,
          date: vote.date,
          vote: vote.votes[icpsrId!] as "Yea" | "Nay" | "Present" | "Not Voting",
          description: vote.description,
        }));

      conflicts = detectConflicts(industries, memberVotes);
    } catch {
      // Conflicts remain empty array on error
    }
  }

  // Narrative conflict callouts — "say one thing, do another" insight (#109)
  const conflictCallouts = getConflictCallouts(
    id,
    finance,
    keyVotesData as unknown as Array<{
      id: string;
      bill: string;
      title: string;
      description?: string;
      category: string;
      date: string;
      votes: Record<string, string>;
    }>,
    icpsrId
  );

  // Committee data will be integrated from Congress.gov API in a future update
  const committees: Array<{
    name: string;
    role: "Chair" | "Ranking Member" | "Member" | "Vice Chair";
    subcommittees?: string[];
  }> = [];

  // Track which sections have no data yet — used to show a subtle "data pending" footer
  // rather than prominent "coming soon" cards for each empty section.

  // Stock trades loaded client-side via /data/trades/[id].json (75MB file split into per-member files)

  // Financial disclosures from House Clerk
  const financialDisclosures = getMemberDisclosures(id);

  // Alignment data (used for rating schema + social share text)
  const alignmentEnhanced = getMemberAlignmentEnhanced(id);

  // Constituent alignment — "Represents You?" polling vs. voting comparison
  const constituentAlignment = getConstituentAlignment(id);

  // Build list of sections that have no data yet for the subtle footer notice
  const emptySections: string[] = [];
  if (committees.length === 0) emptySections.push("Committee Memberships");
  // Stock trades + financial disclosures: components handle their own empty states

  const getPartyBadgeClass = (party: string) => {
    switch (party) {
      case "D":
        return "bg-blue-100 text-blue-700";
      case "R":
        return "bg-red-100 text-red-700";
      case "I":
        return "bg-purple-100 text-purple-700";
      default:
        return "bg-slate-100 text-slate-700";
    }
  };

  const getPartyName = (party: string) => {
    switch (party) {
      case "D":
        return "Democrat";
      case "R":
        return "Republican";
      case "I":
        return "Independent";
      default:
        return party;
    }
  };

  // Schema.org structured data
  const chamberName = member.chamber === "house" ? "U.S. House of Representatives" : "U.S. Senate";
  const chamberUrl = member.chamber === "house" ? "/house" : "/senate";
  const jobTitle = member.chamber === "house" 
    ? `U.S. Representative for ${member.state}${member.district ? `-${member.district}` : ""}` 
    : `U.S. Senator from ${member.state}`;
  
  const personSchema = generatePersonSchema({
    name: member.full_name,
    jobTitle: jobTitle,
    description: `${getPartyName(member.party)} ${member.chamber === "house" ? "Representative" : "Senator"}. View voting record, campaign finance data, and accountability metrics.`,
    image: member.photo_url ?? undefined,
    url: `/rep/${id}`,
    party: member.party,
    state: member.state,
    district: member.district ? String(member.district) : undefined,
    chamber: member.chamber,
    affiliation: {
      name: chamberName,
      url: chamberUrl,
    },
  });

  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "/" },
    { name: "Congress", url: "/congress" },
    { name: member.full_name, url: `/rep/${id}` },
  ]);

  // Rating schema disabled per #84 (alignment scoring paused)
  const ratingSchema = null;

  return (
    <div className="min-h-screen bg-white">
      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={structuredDataScript(personSchema)}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={structuredDataScript(breadcrumbSchema)}
      />
      {ratingSchema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={structuredDataScript(ratingSchema)}
        />
      )}
      {/* Header Section */}
      <section className="bg-gradient-to-b from-slate-50 to-white border-b border-slate-200 py-12 md:py-16">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          {/* Breadcrumb */}
          <div className="mb-6">
            <Link
              href="/congress"
              className="text-slate-600 hover:text-slate-900 text-base font-medium transition"
            >
              ← Back to Representatives
            </Link>
          </div>

          <div className="flex flex-col md:flex-row items-start gap-8">
            {/* Photo */}
            <RepresentativeImage
              bioguideId={member.bioguide_id}
              fullName={member.full_name}
              party={member.party}
              photoUrl={member.photo_url}
              size="lg"
            />

            <div className="flex-1">
              {/* Name */}
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-black tracking-tight text-slate-900 mb-3 leading-tight">
                {member.full_name}
              </h1>

              {/* Party & District */}
              <div className="flex flex-wrap items-center gap-3 mb-6">
                <span
                  className={`px-3 py-1.5 rounded-lg font-bold text-sm ${getPartyBadgeClass(
                    member.party
                  )}`}
                >
                  {getPartyName(member.party)}
                </span>
                {(() => {
                  const leaderRole = isLeader(id);
                  return leaderRole ? (
                    <span className="px-3 py-1.5 rounded-lg font-bold text-sm bg-amber-100 text-amber-800 border border-amber-300 flex items-center gap-1.5">
                      <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
                      </svg>
                      {leaderRole.role}
                    </span>
                  ) : null;
                })()}
                <span className="text-lg text-slate-600">
                  {member.state}
                  {member.district ? `-${member.district}` : ""} •{" "}
                  {member.chamber === "house" ? "Representative" : "Senator"}
                </span>
              </div>

              {/* Accountability Verdict — answers "Who does this rep serve?" above the fold */}
              {(finance !== null || conflicts.length > 0) && (
                <div className="mb-5">
                  <RepVerdictBadge
                    pacPct={finance?.pac_percentage ?? null}
                    highConflicts={conflicts.filter(c => c.conflictSeverity === "high").length}
                    totalConflicts={conflicts.length}
                  />
                </div>
              )}

              {/* Quick Stats Row */}
              <div className="grid grid-cols-3 gap-3 text-sm">
                <div className="bg-slate-50 rounded-lg px-3 py-2 text-center">
                  <div className="font-bold text-slate-900 text-lg tabular-nums">{member.bills_sponsored}</div>
                  <div className="text-slate-500 text-xs">Sponsored</div>
                </div>
                <div className="bg-slate-50 rounded-lg px-3 py-2 text-center">
                  <div className="font-bold text-slate-900 text-lg tabular-nums">{member.bills_cosponsored}</div>
                  <div className="text-slate-500 text-xs">Cosponsored</div>
                </div>
                <div className="bg-slate-50 rounded-lg px-3 py-2 text-center">
                  <div className="font-bold text-slate-900 text-lg tabular-nums">{member.votes_cast}</div>
                  <div className="text-slate-500 text-xs">Votes Cast</div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex flex-wrap gap-3 mt-6">
                <a
                  href={`https://www.congress.gov/member/${member.bioguide_id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-5 py-2.5 bg-blue-600 text-white font-semibold rounded-xl hover:bg-blue-700 flex items-center gap-2 transition-all shadow-md hover:shadow-lg text-sm"
                >
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                  Congress.gov Profile
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 lg:px-8 py-12">
        {/* Conflict Alerts — narrative "say one thing, do another" callouts (#109) */}
        {conflictCallouts.length > 0 && (
          <div className="mb-8">
            <ErrorBoundary context="conflict callout alerts">
              <ConflictCalloutSection
                callouts={conflictCallouts}
                memberName={member.full_name}
              />
            </ErrorBoundary>
          </div>
        )}

        {/* Donor Capture Score — top-level verdict answering "who does this rep work for?" */}
        {(conflicts.length > 0 || finance !== null) && (
          <div className="mb-8">
            <DonorCaptureScore
              conflicts={conflicts}
              finance={finance}
              memberName={member.full_name}
            />
          </div>
        )}

        {/* Constituent Alignment — "Represents You?" section (#111) */}
        {constituentAlignment && constituentAlignment.totalVotesScored > 0 && (
          <div className="mb-8">
            <ErrorBoundary context="constituent alignment">
              <RepresentsYouSection
                alignment={constituentAlignment}
                memberName={member.full_name}
              />
            </ErrorBoundary>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content (2/3 width) */}
          <div className="lg:col-span-2 space-y-8">

            {/* Campaign Finance - Now the main focus */}
            <ErrorBoundary context="campaign finance data">
              <DonorAnalysisSection
                finance={finance}
                memberId={member.bioguide_id}
                memberChamber={member.chamber}
                memberState={member.state}
                percentilesData={donorPercentiles}
              />
            </ErrorBoundary>

            {/* Potential Conflicts of Interest */}
            <ErrorBoundary context="conflict of interest analysis">
              <div id="conflicts">
                <ConflictOfInterestSection conflicts={conflicts} memberName={member.full_name} />
              </div>
            </ErrorBoundary>

            {/* Key Votes — curated votes with descriptions and categories */}
            <ErrorBoundary context="voting record">
              <MemberVotingRecord
                bioguideId={member.bioguide_id}
                icpsrId={icpsrId}
                memberParty={member.party}
                memberName={member.full_name}
                chamber={member.chamber === "house" ? "House" : "Senate"}
                keyVotes={keyVotesData as unknown as Array<{
                  id: string;
                  congress: number;
                  chamber: "House" | "Senate";
                  rollnumber: number;
                  date: string;
                  bill: string;
                  title: string;
                  description: string;
                  category: string;
                  yea_count: number;
                  nay_count: number;
                  result: string;
                  votes: Record<string, string>;
                }>}
              />
            </ErrorBoundary>

            {/* Policy Positions: Says vs Does — REMOVED: Scoring needs redesign (issue #84) */}

            {/* Stock Trades — loaded client-side from /data/trades/[bioguideId].json */}
            <ErrorBoundary context="stock trades">
              <StockTradesSection
                bioguideId={id}
                memberName={member.full_name}
              />
            </ErrorBoundary>

            {/* Financial Disclosures */}
            <ErrorBoundary context="financial disclosures">
              <FinancialDisclosuresSection
                disclosures={financialDisclosures}
                memberName={member.full_name}
              />
            </ErrorBoundary>

            {/* Scandals & Controversies */}
            <ErrorBoundary context="scandals">
              <ScandalsSection
                bioguideId={member.bioguide_id}
                memberName={member.full_name}
                maxVisible={3}
              />
            </ErrorBoundary>

            {/* In Development Features */}
            <InDevelopmentBanner
              features={[
                {
                  name: "Say vs Do Analysis",
                  description: "Track whether representatives follow through on their campaign promises",
                },
                {
                  name: "Net Worth Tracking",
                  description: "Monitor changes in representatives' wealth during their time in office",
                },
                {
                  name: "Dark Money Tracking",
                  description: "Identify undisclosed and hard-to-trace campaign funding sources",
                },
              ]}
            />

            {/* Data Pending Notice — subtle footer instead of prominent "coming soon" cards */}
            {emptySections.length > 0 && (
              <div className="mt-4 py-4 border-t border-slate-200">
                <p className="text-sm text-slate-400 font-mono">
                  Data pending: {emptySections.join(", ")}.{" "}
                  <a href="/methodology" className="text-teal-600 hover:underline ml-1">
                    Learn about our data sources →
                  </a>
                </p>
              </div>
            )}
          </div>

          {/* Sidebar (1/3 width) */}
          <aside className="space-y-8">
            {/* Position-to-Vote Alignment — REMOVED: Scoring needs redesign (issue #84) */}
            

            {/* Latest News — powered by Perplexity Sonar via OpenRouter */}
            <LatestNews
              bioguideId={member.bioguide_id}
              memberName={member.full_name}
              staticCache={newsCache}
            />

            {/* Committee Memberships — only render when data is available */}
            {committees.length > 0 && (
              <CommitteeMemberships committees={committees} />
            )}

            {/* Social Share */}
            <SocialShare
              title={`${member.full_name} - Accountability Dashboard`}
              text={`Check out ${member.full_name}'s voting record and campaign finance data on the Accountability Dashboard.`}
              url={`https://reps.arialabs.ai/rep/${member.bioguide_id}`}
            />

            {/* External Links */}
            <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm hover:shadow-lg transition-all duration-300">
              <h4 className="text-xl font-black uppercase tracking-tight text-slate-900 mb-4">
                Resources
              </h4>
              <div className="space-y-2 text-sm">
                <a
                  href={`https://www.congress.gov/member/${member.bioguide_id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 font-semibold hover:underline block"
                >
                  Congress.gov Profile →
                </a>
                <a
                  href={`https://bioguide.congress.gov/search/bio/${member.bioguide_id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 font-semibold hover:underline block"
                >
                  Biographical Directory →
                </a>
                <a
                  href={`https://www.opensecrets.org/search?q=${encodeURIComponent(member.full_name)}&type=politicians`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 font-semibold hover:underline block"
                >
                  OpenSecrets Profile →
                </a>
                <a
                  href={`https://www.fec.gov/data/candidates/?q=${encodeURIComponent(member.last_name)}&office=${member.chamber === 'house' ? 'H' : 'S'}&state=${member.state}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 font-semibold hover:underline block"
                >
                  FEC Filings →
                </a>
              </div>
            </div>

            {/* Data Sources */}
            <div className="bg-slate-50 rounded-xl p-6 border border-slate-200">
              <h4 className="font-bold text-slate-900 mb-3">📊 Data Sources</h4>
              <ul className="text-sm text-slate-600 space-y-1">
                <li>• Congress.gov API</li>
                <li>• Federal Election Commission</li>
                <li>• Voteview (voting records)</li>
              </ul>
              <p className="text-xs text-slate-400 mt-3">
                Data updated regularly. Last build: {new Date().toLocaleDateString()}
              </p>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
